#!/bin/sh

exec 2>&1

CONFIG="{{pkg.svc_config_path}}/inspec_exec_config.json"
INTERVAL="{{cfg.interval}}"
LOG_FILE="{{pkg.svc_path}}/logs/inspec_log.txt"
PROFILE_IDENT="{{pkg.origin}}/{{pkg.name}}"
PROFILE_PATH="{{pkg.path}}/{{pkg.name}}-{{pkg.version}}.tar.gz"

while true; do
  echo "Executing ${PROFILE_IDENT}"
  #exec inspec exec ${PROFILE_PATH} --json-config ${CONFIG} 2>&1 | tee ${LOG_FILE}
  if [ "{{cfg.chef_license.acceptance}}" == "accept" ]
  then
    echo "Executing ${PROFILE_IDENT}"
 #   exec inspec exec ${PROFILE_PATH} --attrs ${WAIVERS} --json-config ${CONFIG} 2>&1 --chef-license=accept-no-persist | tee ${LOG_FILE}
    exec inspec exec ${PROFILE_PATH} --json-config ${CONFIG} 2>&1 --chef-license=accept-no-persist | tee ${LOG_FILE}
  else
    echo "You have not accepted the chef license."
    echo "  in order to run this package you must"
    echo "  set the chef_license config in your"
    echo "  default.toml"
    $exit_code=172
  fi

  exit_code=$?
  if [ $exit_code -eq 1 ]; then
    echo "InSpec run failed."
  else
    echo "InSpec run completed successfully."
    if [ $exit_code -eq 0 ]; then
      echo "No controls failed or were skipped."
    elif [ $exit_code -eq 100 ]; then
      echo "At least 1 control failed."
    elif [ $exit_code -eq 101 ]; then
      echo "No controls failed but at least 1 skipped."
    fi
  fi
  echo "Results are logged here: ${LOG_FILE}"

  echo "Sleeping for ${INTERVAL} seconds"
  sleep ${INTERVAL}
done
